### ISSUE TITLE
Yubikey 4 OTP disable fails

### ISSUE THREAD

**Issue by kushaldas** [SUNET/tugpgp#11]
```
$ ./Tugpgp-0.0.4-x86_64.AppImage 
QQmlExpression: Expression file:///tmp/.mount_Tugpgp8PjLNa/usr/app/tugpgp/main.qml:132:13 depends on non-NOTIFYable properties:
    Process::PublicKey
Traceback (most recent call last):
  File "/tmp/.mount_Tugpgp8PjLNa/usr/app/tugpgp/app.py", line 155, in save_adminpin
    rjce.disable_otp_usb()
johnnycanencrypt.CryptoError: CardError: Error Failed to change OTP mode
file:///tmp/.mount_Tugpgp8PjLNa/usr/app/tugpgp/main.qml:174: Error: CardError: Error Failed to change OTP mode
Traceback (most recent call last):
  File "/tmp/.mount_Tugpgp8PjLNa/usr/app/tugpgp/app.py", line 155, in save_adminpin
    rjce.disable_otp_usb()
johnnycanencrypt.CryptoError: CardError: Error Failed to change OTP mode
file:///tmp/.mount_Tugpgp8PjLNa/usr/app/tugpgp/main.qml:174: Error: CardError: Error Failed to change OTP mode
```

**Comment by kushaldas** [comment]
We don't have support for Yubikey 4 in the upstream library for now, we will suppress the error for Yubikey4 for now.
